/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class metro4j_Metro4J */

#ifndef _Included_metro4j_Metro4J
#define _Included_metro4j_Metro4J
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     metro4j_Metro4J
 * Method:    Do_Metro
 * Signature: (ZDD[DJ[J[D[D[D[D[D[D[D[D[D[D[D[D[D[D[J[ZDJJZJ)Lmetro4j/MetroResult;
 */
JNIEXPORT jobject JNICALL Java_metro4j_Metro4J_Do_1Metro
  (JNIEnv *, jclass, jboolean, jdouble, jdouble, jdoubleArray, jlong, jlongArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jlongArray, jbooleanArray, jdouble, jlong, jlong, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class metro4j_MetroResult */

#ifndef _Included_metro4j_MetroResult
#define _Included_metro4j_MetroResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
